dimension: 4000
num_samples: 2000
kappa: 10.0
output_dir: "/scratch/aplesner/data_samples/"
implementation: "torch"
dtype: "float16"
random_mean_direction: true
device: "auto"
seed: 1
verbosity: "info"
wandb_project: "vmf-estimation"
wandb_offline: false

