dimension: 8000
num_samples: 2000
kappa: 10.0
output_dir: "data_samples/"
implementation: "torch"
random_mean_direction: false
device: "auto"
seed: 1
verbosity: "debug"
wandb_project: "vmf-estimation"
wandb_offline: false

