dimension: 4000
num_samples: 2000
kappa: 10.0
output_dir: "data_samples/"
implementation: "torch"
dtype: "float32"
random_mean_direction: true
device: "auto"
seed: 1
verbosity: "debug"
wandb_project: "vmf-estimation"
wandb_offline: false

